### PR TITLE
Add CI script for snippet templates

### PR DESCRIPTION
**Pull request by RaphGL**
This PR adds a Python script that converts code snippet templates into language specific snippets. 
Goal: Reduce maintenance cost. 

By having all code snippets in one place, any change or fix to the snippets will trickle down to all translations instead of having to tediously fix the issue for every single translation provided.

For examples on how this can be used check the `/docs/snippets/chapter-1` directory.

### CODE REVIEW

**Comment by RaphGL** [comment]
> `test-out/test-c1.zig:1:1: error: expected type expression, found '{'`

Is this a test running failure? This looks like the templates
```md
# something
{{ snippet_name}}
```

If we want to keep using the same system for tests instead of check them on the snippets directory we now have to run the `translate_ci.py` so it can expand the templates. (caution: it overrides all the markdown files with the expanded versions for now)

**Comment by rofrol** [comment]
> Is this a test running failure

Yes. The test is run here https://github.com/zighelp/zighelp/blob/4a4c26821b58e769b34678eddb7ffabb18b36cf8/.github/workflows/pr.yml#L20

**Comment by RaphGL** [comment]
> > Is this a test running failure
> 
> Yes. The tests are run here https://github.com/zighelp/zighelp/blob/4a4c26821b58e769b34678eddb7ffabb18b36cf8/.github/workflows/pr.yml#L20

I see, I'll work on it later today. I first need to fix snippets with no translations rendering as empty snippets.

After that I'll try adding this script as a step before running the tests, that should fix the error.

**Comment by RaphGL** [comment]
I've fixed the snippets, I want to also add a prompt that makes the user type some sort of confirmation to avoid overwriting the files unintentionally and provide a `-y` flag so it can be run without it through the CI.

As for the CI, I think this should work?
```yaml
  test:
    strategy:
      matrix:
        # disabling windows-latest for now. zig fmt --check gives strange results
        # os: [ubuntu-latest, macos-latest, windows-latest]
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v2
      - uses: goto-bus-stop/setup-zig@v2
      - run: |
          python translate_ci.py
          zig run test-out.zig
          zig test do_tests.zig
          zig fmt --check test-out
  mkdocs-build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.11.4
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV
      - uses: actions/cache@v3
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-
      - run: pip install -r requirements.txt
      - run: python translate_ci
      - run: mkdocs build --strict
```
From what I've understood the CI jobs are isolated so I'd have to run it inside the jobs for it to work. I'll look more into that tomorrow as I did not have time today.

**Comment by rofrol** [comment]
I have modified github workflows a bit.
My intention was to have one workflow for PRs with tests.
And another when commit pushed on master.

I wanted to avoid running tests twice, if the merge was done from pull request.

I could add another workflow on pull request that could check if PR was closed successfully, but also wanted to preserve test and deploy when pushed directly to master.

And that took me like one day to figure this out. I needed to use another action to have `pr_found`.

Anyway. It works :)

**Comment by rofrol** [comment]
So you may need to add `python translate_ci.py` in those two workflows.

**Comment by RaphGL** [comment]
@rofrol I'm ready to merge, we just need to check if the workflow is working correctly. 
Next step if remove all snippets from the translations and put the templates in their places as shown in the few snippets I've done that for already.

**Comment by rofrol** [comment]
CI/CD failed:

```
  File "/home/runner/work/zighelp/zighelp/translate_ci.py", line 7, in <module>
    import tomllib as toml
ModuleNotFoundError: No module named 'tomllib'
```

I have described how to install python packages https://github.com/zighelp/zighelp#generate-docs-locally

Can you add tomlib and other missing python packages to requirements.txt?

**Comment by RaphGL** [comment]
@rofrol the script only uses the standard library and dependencies that were already on `requirements.txt` (namely Colorama for the user warning and Jinja2 for templating)

According to python's documentation, tomllib has been part of the standard library since 3.11: https://docs.python.org/3/library/tomllib.html

I think the issue might be that the test itself does not state that 3.11 is the python we're depending on whereas the deployment (mkdocs) does? I'm not sure what `ubuntu-latest`'s version is.

**Comment by rofrol** [comment]
But github action job states that:

```yml
      - uses: actions/setup-python@v4
        with:
          python-version: 3.11.4
```

Strange.

**Comment by rofrol** [comment]
Maybe we can use in step `python --version` to show it in log?

**Comment by rofrol** [comment]
So I have added `python --version` to pr.yml and it shows this:

```
Run python --version
  
Python 3.11.4
```

**Comment by RaphGL** [comment]
can you test the CI again for me? I think this might be the issue (I also consulted with some pythonistas and we could not narrow it down to something else, as it worked fine on my machine as well). I've added a setup step for python on the test jobs. 

If this doesn't work we can temporarily use [toml](https://pypi.org/project/toml/) which has the same API as tomllib until we can solve the issue.

**Comment by rofrol** [comment]
I see first error on lone 179:

test-out/test-c1.zig:8:9: error: use of undeclared identifier 'expect'

**Comment by RaphGL** [comment]
for some reason the `test-out.zig` script seems to be stripping the initial import in the test suite

```
raph@fedora ~/Projects/ZigHelp % head -n 10 test-out/test-c1.zig          
const expect = @import("std").testing.expect;

test "while" {
    var i: u8 = 2;
    while (i < 100) {
        i *= 2;
    }
    try expect(i == 128);
}

raph@fedora ~/Projects/ZigHelp % python translate_ci.py -y                
raph@fedora ~/Projects/ZigHelp % head -n 10 test-out/test-c1.zig
const expect = @import("std").testing.expect;

test "while" {
    var i: u8 = 2;
    while (i < 100) {
        i *= 2;
    }
    try expect(i == 128);
}

raph@fedora ~/Projects/ZigHelp % zig run test-out.zig                         
raph@fedora ~/Projects/ZigHelp % head -n 10 test-out/test-c1.zig


test "while" {
    var i: u8 = 2;
    while (i < 100) {
        i *= 2;
    }
    try expect(i == 128);
}
```

**Comment by RaphGL** [comment]
Also as a note this should not be merged yet as the loop I added for snippets with no translations seem to be resulting in some of the snippets being rendered as empty (I'll look into why's that happening tomorrow). The bug is "fixed" by removing one of the loops, resulting in the other set of snippets being rendered.

**Comment by RaphGL** [comment]
All tests have been passed :)
image

**Review by rofrol — APPROVED** [review]

**Comment by rofrol** [comment]
Thanks.

I don't know much Python but from glancing over it looks ok. So I rely on you for that :)

Probably there needs to be some description for contributors
- how the snippets are laid out
- how to add new snippets.


Also now there is no need to specify python version in github action, as I have added `.python-version`, but I didn't want to block the PR any longer.

In the future I think we should rewrite it in zig (RIIZ) :D

**Comment by RaphGL** [comment]
> I don't know much Python but from glancing over it looks ok. So I rely on you for that :)
Sure, I'm open to helping with maintaining the script if needed.

> Probably there needs to be some description for contributors
>
>    - how the snippets are laid out
>    - how to add new snippets.

The way it works is it reads the `${SNIPPET_DIR}/Chapter-X` and goes through each snippet there, the `.zig` file (snippet) has to have the same name as the directory it's in, all snippets are in that directory with the same name as the directory of the translations, so if you have `docs/pt_br` your snippet translations file would be `pt_br.toml` 

For the template itself, you just need to put the name of the snippet you want in there like so `{{ generic_function }}`, the script goes through all the files and figures out what language should get what version of the snippet.

I can make a PR for this later today or tomorrow if you want. 

> In the future I think we should rewrite it in zig (RIIZ) :D
Agreed, I was going to do it in zig but I decided not to cause I couldn't decide on which libraries to use and I saw that you already depended on python to build the project, so I went with those.

**Comment by rofrol** [comment]
Yes, please add a PR. Some straight instructions for translators would be great.

**Comment by rofrol** [comment]
> Agreed, I was going to do it in zig but I decided not to cause I couldn't decide on which libraries to use and I saw that you already depended on python to build the project, so I went with those.

Sure. We have a first working version. That's a start👍

**Pull request merged**
